name: "Push image to GitHub Registry"

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/mlcdf/sftptest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/mlcdf/www:buildcache
          cache-to: type=registry,ref=ghcr.io/mlcdf/www:buildcache,mode=max